# Generated by Django 3.1.7 on 2021-03-19 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名稱')),
            ],
        ),
        migrations.CreateModel(
            name='MainProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名稱')),
            ],
        ),
        migrations.CreateModel(
            name='OriginPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('weight', models.PositiveIntegerField()),
                ('taste', models.TextField()),
                ('description', models.TextField()),
                ('roast', models.CharField(choices=[('Light', '極淺度烘焙'), ('Cinnamon', '淺度烘焙'), ('Medium', '中度烘焙'), ('High', '中度微深烘焙'), ('City', '中深度烘焙'), ('Full-City', '微深度烘焙'), ('French', '極深烘焙'), ('Italian', '極深度烘焙')], max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('grindings', models.ManyToManyField(to='coffees.Grinding')),
                ('main_processing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffees.mainprocessing')),
                ('origin_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffees.originplace')),
            ],
        ),
    ]
