# Generated by Django 3.1.7 on 2021-04-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainProcessing',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='coffee',
            options={'verbose_name': '咖啡', 'verbose_name_plural': '咖啡'},
        ),
        migrations.AlterModelOptions(
            name='grinding',
            options={'verbose_name': '標籤', 'verbose_name_plural': '標籤'},
        ),
        migrations.AlterModelOptions(
            name='originplace',
            options={'verbose_name': '產地', 'verbose_name_plural': '產地'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '標籤', 'verbose_name_plural': '標籤'},
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='grindings',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='main_processing',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='taste',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='weight',
        ),
        migrations.AddField(
            model_name='coffee',
            name='tags',
            field=models.ManyToManyField(to='coffees.Tag', verbose_name='標籤'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='origin_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffees.originplace', verbose_name='產地'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.PositiveIntegerField(verbose_name='價格'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='roast',
            field=models.CharField(choices=[('Light', '極淺度烘焙'), ('Cinnamon', '淺度烘焙'), ('Medium', '中度烘焙'), ('High', '中度微深烘焙'), ('City', '中深度烘焙'), ('Full-City', '微深度烘焙'), ('French', '極深烘焙'), ('Italian', '極深度烘焙')], max_length=10, verbose_name='烘培程度'),
        ),
    ]
